### PR TITLE
Artefact upload

### PR DESCRIPTION
**Pull request by mfherbst**

### CODE REVIEW

**Review by maxscheurer — APPROVED** [review]

**Comment by maxscheurer** [comment]
Just FYI, draft releases are not publicly downloadable even when the repo is public. But probably you already know that 😄

**Comment by mfherbst** [comment]
Yes, but I can later make it public. It's just a safeguard to not mess up.

**Comment by maxscheurer** [comment]
I know 👍 I was just not sure whether the release can be used by GHA on the adcc repo for download.

**Comment by mfherbst** [comment]
Now it can. I just made it public ;)

**Pull request merged**
