### PR TITLE
[WIP] OpenMP fix for Conda/Linux

### PR DESCRIPTION
**Pull request by maxscheurer**

### CODE REVIEW

**Comment by mfherbst** [comment]
What's the status here? Should this be merged?

**Comment by maxscheurer** [comment]
No, I was not able to fix the conda build on Linux yet... The problem is that OpenMP libraries are not found by CMake. I could reproduce it locally, but no success on getting it to work.

**Comment by mfherbst** [comment]
Might be stupid, but: https://github.com/adc-connect/libtensor/runs/4305413231?check_suite_focus=true#step:6:64

Looks like it is found?

**Comment by maxscheurer** [comment]
That's the normal build.... I mean the conda deployment build [here](https://github.com/adc-connect/libtensor/runs/4305414506?check_suite_focus=true#step:7:398)...

**Comment by mfherbst** [comment]
Ah ok, I see. That indeed looks annoying. On first look I have no idea.

**Pull request closed without merging**
