### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by maxscheurer**

### CODE REVIEW

**Comment by maxscheurer** [comment]
OpenMP on macOS seems to be broken... cool...

**Comment by mfherbst** [comment]
Thanks very much for investigating.

Not that I can be of an aweful lot of help here, but it could have something to with the warning flags that we employ (which I believe are a little stronger than the default libtensor things). See also this SO thread: https://stackoverflow.com/questions/46414660/macos-cmake-and-openmp. Perhaps similarly disabling warning for unused args could help ?

**Comment by mfherbst** [comment]
Klampf. Thanks for trying @maxscheurer !

**Comment by maxscheurer** [comment]
Thanks for the suggestion 😄 I'm trying to reproduce this locally, but without success so far.

**Review by mfherbst — APPROVED** [review]
Yeah ok, seems fair.

**Pull request merged**
